#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
var=$(hostname)
	new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
	new_string2="server {\n\tadd_header X-Served-By $var;"

	apt-get update -y
	apt-get install nginx -y
	echo "Hello World!" > /usr/share/nginx/html/index.html
	mkdir -p /var/www/html
	echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
	sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
# Your web-02 server are returning a custom X-Served-By in their HTTP response.
curl -sI http://34.198.248.145 | grep -i X-Served-By

#Your web-01 server are returning a custom X-Served-By in their HTTP response.
curl -sI http://34.207.222.131 | grep -i34.207.222.131	

	sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
	
	sudo service nginx start
