#!/usr/bin/env bash
# Configures  Nginx so that its HTTP response contains a custom header 
sudo apt-get update
sudo apt-get install -y nginx 
sudo ufw allow 'Nginx Http'

HOSTNAME=$(hostname)

echo "hello world" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
        index index.html index.htm;

	server_name _;
	add_header X-Served-By $HOSTNAME;
        location / {
        try_files $uri $uri/ =404;
    }
}" > default_file

mv -f default_file /etc/nginx/sites-available/default

sudo systemctl restart nginx
