#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-by $HOSTNNAME;

	root  /etc/nginx/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
